services:
  tls_test:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always

  nginx:
    image: nginx:1.27.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_conf/configs:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/truepotatoes.ru:/etc/nginx/certs
    depends_on: 
      - tls_test